place = (input("enter any place: "))
adjective = (input("enter any adjective: "))
name = (input("enter any name: "))
othername = (input("enter another name: "))
animal = (input("enter any animal: "))
number = int(input("enter any number: "))
othernumber = int(input("enter another number: "))
print("Once upon a time, " + name + " and " + othername + " took a walk to " + place + ".")
print("While at " + place + ", they saw " + str(number) + " " + animal + "s.")
print("They were shocked at the amount of " + adjective + " " + animal + "s they saw.")
print(name + " told " + othername + " That if there were " + str(othernumber) + " more " + animal + "s, there would be" + " " + str(number + othernumber) + " " + animal + "s.")
print(othername + " said that if there were that many " + animal + "s, they would have to run away.")
print(name + " and " + othername + " spent a bit more time at " + place + " and then went home.")